### ISSUE TITLE
Questionable W3C Link Checker Errors

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-discovery#233] opened 2021-11-10 17:22 UTC
W3C Link Checker at https://validator.w3.org/checklink?uri=https%3A%2F%2Fw3c.github.io%2Fwot-discovery&hide_type=all&depth=&check=Check gives one broken link due to the fragments used on it. However, I can resolve both the URLs manually. Maybe I do not see the error or W3C Link Checker has a bug but wanted to post it as an issue anyway since I was doing this for all the specs.

**Comment by mmccool** [comment] 2022-04-11 14:51
Is this still a problem?  @ashimura

**Comment by mmccool** [comment] 2022-04-11 14:54
It seems this may be because applying this to the ReSpec version won't work, it has to be done on the static version.  Kaz will look into it, but if it's showing an error on the ReSpec version that is expected.

Propose closing; we can deal with the link checker when we publish the next WD.

**Comment by egekorkan** [comment] 2022-04-12 10:57
I think that my initial comment is outdated anyway. I think we should simply fix based on @ashimura comments above since generating the static document fixes some links. E.g. the error below is not present in the static version:
![grafik](https://user-images.githubusercontent.com/20195407/162945395-9aa48343-8d20-4398-b3ae-0ddd08f2288f.png)

**Comment by mmccool** [comment] 2022-08-23 13:42
I saw this error as well but I think the issue is the *Hydra* spec is using ReSpec internally and is not static.  Anyway, the links work if you check them manually, so I think we can just override these errors.   That's what I did for the last WD anyway, and we may have to do it for the CR, too.

**Closed** 2023-03-20 13:09 UTC
Labels: Propose Closing
